### ISSUE TITLE
name search

### ISSUE THREAD

**Issue by Amalhayek99** [WebAhead11/PSG-PlayerSearch#2]
the string "erg" should not give any results
by the way, it gives(erg in the middle of a name)
serigo rico and serigo ramos

**Comment by Omar2220** [comment]
It's a matter of opinion and we choose to be more user-friendly and give the user every possible name he could search for, who knows maybe he has forgotten the full name and remembers only some letters of the first name and last name, so I think it's not exactly an issue.
